### ISSUE TITLE
Needs a logo

### ISSUE THREAD

**Issue by jbergstroem** [jnordberg/nsync#1]
Quick! Most important task.

**Comment by jbergstroem** [comment]
A few suggestions comes to mind: https://www.google.com.au/search?q=nsync&tbm=isch

**Comment by jnordberg** [comment]
![nsync](http://xn--bl-wia.se/nsync.svg)

:grinning: What about something like this?

**Comment by jbergstroem** [comment]
IMHO needs more 3d. And Nsync runs with blue!!

**Comment by jbergstroem** [comment]
Close your eyes. Isn't that the colour blue running through your cables?

**Comment by jnordberg** [comment]
Needs to have green, node has green.

**Comment by jnordberg** [comment]
![nsync](http://xn--bl-wia.se/nsync2.svg?)

**Comment by jnordberg** [comment]
![nsync](http://xn--bl-wia.se/nsync3.svg?)

**Comment by jbergstroem** [comment]
Getting there :beer:

**Comment by jnordberg** [comment]
![nsync](http://xn--bl-wia.se/nsync5.svg)

**Comment by jnordberg** [comment]
![nsync](http://xn--bl-wia.se/nsync8.svg)

**Comment by jnordberg** [comment]
Done! :racehorse:
